### ISSUE TITLE
Null Pointer Exception when attempting to make a world

### ISSUE THREAD

**Issue by DichoMire** [AllTheMods/All-the-mods-7-Sky#181]
Hi, I downloaded the 1.0.7 version of ATM 7 from CurseForge. Upon launching, I get into the main menu and click single player. It takes me directly to the create world screen. I make a world. The game gets stuck on 0% world creation. When I kill the task, I get the following in the crash report:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/18/22, 12:28 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getCapability(net.minecraftforge.common.capabilities.Capability)" because "level" is null
	at com.technicalitiesmc.scm.circuit.server.CircuitCache.get(CircuitCache.java:89) ~[SuperCircuitMaker2-0.2.9+1.18.2.jar%23239!/:0.2.9] {re:classloading}
	at com.technicalitiesmc.scm.circuit.server.CircuitCache.tick(CircuitCache.java:102) ~[SuperCircuitMaker2-0.2.9+1.18.2.jar%23239!/:0.2.9] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:953) ~[forge-1.18.2-40.1.79-universal.jar%23266!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

Let me know if you need anything else.

**Comment by Mitchell5200** [comment]
Transferred to atm7 sky.
Please provide a full crashlog

**Comment by DichoMire** [comment]
Thank you for the transfer, Mitchell.

This is the full crash report:
[crash-2022-09-18_12.28.09-server.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9593574/crash-2022-09-18_12.28.09-server.txt)

Here is the content of my game output:
[output1.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9593627/output1.txt)

It's limited to 1000 lines though.
