### ISSUE TITLE
[ATM7 sky 1.2.3] in servers Stuck on Kubejs

### ISSUE THREAD

**Issue by SpongeFun0721** [AllTheMods/All-the-mods-7-Sky#477]
container@P73R~ java -version
Picked up _JAVA_OPTIONS: -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.ldap.object.trustURLCodebase=false -Djava.naming.factory.initial=Fuck.Log4j2
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.3.6.1 (build 17.0.3+6-LTS, mixed mode, sharing)
container@19345~ java -Xms128M -Xmx10240M -jar server.jar
Picked up _JAVA_OPTIONS: -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.ldap.object.trustURLCodebase=false -Djava.naming.factory.initial=Fuck.Log4j2
Picked up _JAVA_OPTIONS: -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.ldap.object.trustURLCodebase=false -Djava.naming.factory.initial=Fuck.Log4j2
2024-01-04 22:50:20,412 main WARN Advanced terminal features are not available in this environment
[22:50:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, nogui]
[22:50:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.3 by Amazon.com Inc.
[22:50:20] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[22:50:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.10/fmlcore-1.18.2-40.2.10.jar is missing mods.toml file
[22:50:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.10/javafmllanguage-1.18.2-40.2.10.jar is missing mods.toml file
[22:50:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.10/lowcodelanguage-1.18.2-40.2.10.jar is missing mods.toml file
[22:50:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.10/mclanguage-1.18.2-40.2.10.jar is missing mods.toml file
[22:50:21] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[22:50:24] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[22:50:24] [main/ERROR] [mixin/]: Mixin config tklib.mixin.json does not specify "minVersion" property
[22:50:25] [main/ERROR] [mixin/]: Mixin config myrtrees-common.mixins.json does not specify "minVersion" property
[22:50:25] [main/ERROR] [mixin/]: Mixin config supercircuitmaker.mixin.json does not specify "minVersion" property
[22:50:25] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.thevortex.allthetweaks.mixin.MixinConnector]
[22:50:25] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[22:50:25] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[22:50:25] [main/WARN] [mixin/]: Reference map 'compactmachines.refmap.json' for compactmachines.mixin.json could not be read. If this is a development environment you can ignore this message
[22:50:25] [main/WARN] [mixin/]: Reference map 'myrtrees-common-refmap.json' for myrtrees-common.mixins.json could not be read. If this is a development environment you can ignore this message
[22:50:25] [main/WARN] [mixin/]: Reference map 'supercircuitmaker.refmap.json' for supercircuitmaker.mixin.json could not be read. If this is a development environment you can ignore this message
[22:50:25] [main/WARN] [mixin/]: Reference map 'insanelib.refmap.json' for insanelib.mixins.json could not be read. If this is a development environment you can ignore this message
[22:50:25] [main/WARN] [mixin/]: Reference map 'bloodmagic.refmap.json' for bloodmagic.mixins.json could not be read. If this is a development environment you can ignore this message
[22:50:25] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/world/inventory/AnvilMenu
[22:50:25] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching FishingHook#catchingFish
[22:50:26] [main/WARN] [mixin/]: Error loading class: mezz/jei/transfer/RecipeTransferUtil (java.lang.ClassNotFoundException: mezz.jei.transfer.RecipeTransferUtil)
[22:50:26] [main/WARN] [mixin/]: @Mixin target mezz.jei.transfer.RecipeTransferUtil was not found polymorph_integrations.mixins.json:jei.MixinRecipeTransferUtil
[22:50:26] [main/WARN] [mixin/]: Error loading class: net/dries007/tfc/common/items/TorchItem (java.lang.ClassNotFoundException: net.dries007.tfc.common.items.TorchItem)
[22:50:26] [main/WARN] [mixin/]: @Mixin target net.dries007.tfc.common.items.TorchItem was not found allthetweaks.mixins.json:TFCTorch
[22:50:26] [main/WARN] [mixin/]: Error loading class: com/eerussianguy/firmalife/common/items/JarsBlockItem (java.lang.ClassNotFoundException: com.eerussianguy.firmalife.common.items.JarsBlockItem)
[22:50:26] [main/WARN] [mixin/]: @Mixin target com.eerussianguy.firmalife.common.items.JarsBlockItem was not found allthetweaks.mixins.json:BreathMint
[22:50:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER
[22:50:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screens/inventory/AbstractContainerScreen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER)
[22:50:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screens.inventory.AbstractContainerScreen was not found findme-common.mixins.json:MixinSlotRenderer
[22:50:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
[22:50:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/particle/ParticleEngine (java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER)
[22:50:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.particle.ParticleEngine was not found findme-common.mixins.json:ParticleEngineAccessor
[22:50:26] [main/INFO] [co.un.de.LoggerHacks/]: !!! SOME LOGGERS HAVE MOVED TO THE DEBUG FILE (Please Include them in your bug reports) !!!
[22:50:28] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/world/inventory/AnvilMenu
[22:50:29] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Patching FishingHook#catchingFish
[22:50:31] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/world/item/EnchantedBookItem
[22:50:31] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction
[22:50:31] [main/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isDiscoverable() in net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction
[22:50:33] [modloading-worker-0/ERROR] [packmenu/]: Running on a dedicated server, disabling mod.
[22:50:33] [modloading-worker-0/INFO] [ne.pe.no.NoVillagerDeathMessages/]: Registering mod: novillagerdm
[22:50:33] [modloading-worker-0/INFO] [PluginManager/]: Scanning classes for industrialforegoing
[22:50:33] [modloading-worker-0/INFO] [PluginManager/]: Found FeaturePluginInstance for class CuriosPlugin for plugin curios
[22:50:33] [modloading-worker-0/INFO] [PluginManager/]: Constructed class CuriosPlugin for plugin curios for mod industrialforegoing
[22:50:33] [modloading-worker-0/INFO] [PluginManager/]: Executing phase CONSTRUCTION for plugin class CuriosPlugin
[22:50:33] [modloading-worker-0/INFO] [PluginManager/]: Executing phase PRE_INIT for plugin class CuriosPlugin
[22:50:34] [modloading-worker-0/INFO] [ir.IronFurnaces/]: Initializing Update Checker...
[22:50:34] [ Iron Furnaces Update Checker/INFO] [ir.IronFurnaces/]: Starting Update Check...
[22:50:34] [modloading-worker-0/INFO] [se.go.ch.re.re.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[22:50:34] [modloading-worker-0/INFO] [PluginManager/]: Executing phase INIT for plugin class CuriosPlugin
[22:50:35] [modloading-worker-0/INFO] [ne.bd.li.ne.NetChannel/]: Initialized network channel 'multiblock' for mod 'bdlib'
[22:50:35] [modloading-worker-0/INFO] [ne.bd.li.ne.NetChannel/]: Initialized network channel 'misc' for mod 'bdlib'
[22:50:35] [modloading-worker-0/INFO] [ne.bd.li.BdLib$/]: Initialized multiblock manager for advgenerators
[22:50:35] [modloading-worker-0/INFO] [ne.bd.li.ne.NetChannel/]: Initialized network channel 'generators' for mod 'advgenerators'
[22:50:35] [modloading-worker-0/WARN] [ne.bl.mo.ba.fo.co.ForgeBalmConfig/]: Config field without expected type, will not validate list content (merchantNames in net.blay09.mods.farmingforblockheads.FarmingForBlockheadsConfigData)
[22:50:35] [modloading-worker-0/INFO] [PluginManager/]: Executing phase POST_INIT for plugin class CuriosPlugin
[Mouse Tweaks] Disabled because not running on the client.
TagKey[minecraft:item / forge:tools]
[22:50:36] [modloading-worker-0/INFO] [showcaseitem/]: Loading config: /home/container/config/showcaseitem-common.toml
[22:50:36] [modloading-worker-0/INFO] [showcaseitem/]: Built config: /home/container/config/showcaseitem-common.toml
[22:50:36] [modloading-worker-0/INFO] [showcaseitem/]: Loaded config: /home/container/config/showcaseitem-common.toml
[22:50:37] [modloading-worker-0/INFO] [Advanced Peripherals/]: AdvancedPeripherals says hello!
[22:50:37] [modloading-worker-0/INFO] [th.ko.te.KotlinForForge/]: Kotlin For Forge Enabled!
[22:50:38] [modloading-worker-0/WARN] [Advanced Peripherals/]: Successfully loaded integration for botania
[22:50:38] [modloading-worker-0/WARN] [Advanced Peripherals/]: Successfully loaded integration for create
[22:50:38] [modloading-worker-0/WARN] [Advanced Peripherals/]: Successfully loaded integration for mekanism
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [Bookshelf/]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[22:50:38] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 40.2.10, for MC 1.18.2 with MCP 20220404.173914
[22:50:38] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v40.2.10 Initialized
[22:50:38] [modloading-worker-0/INFO] [pneumaticcraft/]: Thirdparty integration activated for [theoneprobe,cofh_core,immersiveengineering,computercraft,jei,botania,mekanism,curios,patchouli,create]
[22:50:39] [modloading-worker-0/INFO] [ne.pe.ex.ExMachinis/]: Registering mod: exmachinis
[22:50:41] [modloading-worker-0/INFO] [de.wu.sq.SquatGrow/]: Config loading
[22:50:41] [modloading-worker-0/INFO] [de.wu.sq.SquatGrow/]: Tags: []
[22:50:41] [modloading-worker-0/INFO] [de.wu.sq.SquatGrow/]: Wildcards: []
[22:50:41] [modloading-worker-0/INFO] [co.tt.re.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[22:50:41] [modloading-worker-0/INFO] [co.tt.re.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[22:50:41] [modloading-worker-0/ERROR] [toastcontrol/]: Running on a dedicated server, disabling mod.
[22:50:41] [modloading-worker-0/INFO] [twilightforest/]: Loaded compatibility for mod Tinkers Construct.
[22:50:41] [modloading-worker-0/INFO] [twilightforest/]: Skipped compatibility for mod undergarden.
[22:50:41] [modloading-worker-0/INFO] [KubeJS/]: Looking for KubeJS plugins...
[22:50:41] [modloading-worker-0/INFO] [twilightforest/]: Loaded compatibility for mod Immersive Engineering.
[22:50:41] [modloading-worker-0/INFO] [twilightforest/]: Loaded compatibility for mod Curios.
[22:50:41] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source kubejs
[22:50:42] [modloading-worker-0/ERROR] [KubeJS/]: Failed to load plugin dev.latvian.mods.kubejs.integration.forge.gamestages.GameStagesIntegration from source kubejs: java.lang.NoClassDefFoundError: net/darkhax/gamestages/event/GameStageEvent
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source lazierae2
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source kubejs_thermal
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source ftbic
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source ftbquests
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source kubejs_create
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source kubejs_immersive_engineering
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source exnihilosequentia
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source kubejs_mekanism
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source ponderjs
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source ftbchunks
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Found plugin source modonomicon
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Done in 203.2 ms
[22:50:42] [modloading-worker-0/WARN] [ne.bl.mo.ba.fo.co.ForgeBalmConfig/]: Config field without expected type, will not validate list content (compressBlacklist in net.blay09.mods.craftingtweaks.config.CraftingTweaksConfigData$Common)
[22:50:42] [modloading-worker-0/WARN] [ne.bl.mo.ba.fo.co.ForgeBalmConfig/]: Config field without expected type, will not validate list content (disabledAddons in net.blay09.mods.craftingtweaks.config.CraftingTweaksConfigData$Client)
[22:50:42] [modloading-worker-0/INFO] [KubeJS/]: Loaded common.properties
[22:50:42] [modloading-worker-0/INFO] [Mystical Agriculture/]: Registered plugin: com.blakebr0.mysticalagriculture.lib.ModCorePlugin
[22:50:42] [modloading-worker-0/INFO] [PluginManager/]: Scanning classes for titanium
[22:50:42] [modloading-worker-0/INFO] [Mystical Agriculture/]: Registered plugin: com.blakebr0.mysticalcustomization.lib.ModCorePlugin
[22:50:42] [modloading-worker-0/INFO] [Mystical Agriculture/]: Registered plugin: com.blakebr0.mysticalagradditions.lib.ModCorePlugin
[22:50:43] [modloading-worker-0/INFO] [Rhino Script Remapper/]: Loading Rhino Minecraft remapper...
[22:50:43] [modloading-worker-0/INFO] [de.la.mo.rh.mo.ut.RhinoProperties/]: Rhino properties loaded.
[22:50:43] [modloading-worker-0/INFO] [Rhino Script Remapper/]: Loading mappings for 1.18.2
[22:50:43] [modloading-worker-0/INFO] [Rhino Script Remapper/]: Done in 0.161 s
[22:50:43] [modloading-worker-0/INFO] [ne.pe.py.Pylons/]: Registering mod: pylons
[22:50:43] [modloading-worker-0/INFO] [ne.pe.py.Pylons/]: Registered 1 network packets
[22:50:43] [modloading-worker-0/INFO] [wi.en.ModEngineersDecor/]: Engineer's Decor GIT id #837b867.
Loading schematic: bloodmagic:t_corridor
[22:50:43] [modloading-worker-0/INFO] [PluginManager/]: Scanning classes for functionalstorage
[22:50:43] [modloading-worker-0/INFO] [PluginManager/]: Found FeaturePluginInstance for class TOPPlugin for plugin theoneprobe
[22:50:43] [modloading-worker-0/INFO] [PluginManager/]: Constructed class TOPPlugin for plugin theoneprobe for mod functionalstorage
[22:50:43] [modloading-worker-0/INFO] [PluginManager/]: Executing phase CONSTRUCTION for plugin class TOPPlugin
[22:50:43] [modloading-worker-0/INFO] [PluginManager/]: Executing phase PRE_INIT for plugin class TOPPlugin
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@bb63a3
Loading schematic: bloodmagic:four_way_corridor_loot
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6ed0eb5c
Loading schematic: bloodmagic:four_way_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@46b4da75
Loading schematic: bloodmagic:standard/ore_hold_1
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@d84f3f5
Loading schematic: bloodmagic:straight_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6c62c457
Loading schematic: bloodmagic:overlapped_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@3ec3f105
Loading schematic: bloodmagic:spiral_staircase
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6c29177f
Loading schematic: bloodmagic:standard/water_way
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6c42cd0
Loading schematic: bloodmagic:standard/mine_entrance
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@e137b6b
Loading schematic: bloodmagic:mines/mine_key
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@617b69b2
Loading schematic: bloodmagic:mines/pit
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@37faa019
Loading schematic: bloodmagic:mines/corner_zombie_trap
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@2f925c58
Loading schematic: bloodmagic:mines/split_road
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@5a8fdd90
Loading schematic: bloodmagic:mines/station
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6a617db2
Loading schematic: bloodmagic:mines/downward_tunnel
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@262edf05
Loading schematic: bloodmagic:mines/junction_station
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@1b747077
Loading schematic: bloodmagic:mines/downward_shaft
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@4872a52
Loading schematic: bloodmagic:mines/nature_crossroad
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@517c190a
Loading schematic: bloodmagic:mines/wolf_den
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@21705e1f
Loading schematic: bloodmagic:mines/ore_cavern
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@10723a84
Loading schematic: bloodmagic:mines/straight_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@13ea5e06
Loading schematic: bloodmagic:mines/bent_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@30e57a2e
Loading schematic: bloodmagic:mines/fourway_corridor
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@13606f44
Loading schematic: bloodmagic:mini_dungeon/library
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@4d5d48f5
Loading schematic: bloodmagic:mini_dungeon/armoury
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@31eab677
Loading schematic: bloodmagic:mini_dungeon/farm
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@4f57c8bf
Loading schematic: bloodmagic:mini_dungeon/portal_nether
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@48409949
Loading schematic: bloodmagic:mini_dungeon/crypt
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@5cfbb298
Loading schematic: bloodmagic:standard/challenge_tower
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@4a944f29
Loading schematic: bloodmagic:standard/big_library
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@64ecd05d
Loading schematic: bloodmagic:standard/small_crane
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@46a24ec9
Loading schematic: bloodmagic:standard/small_library
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@22311d18
Loading schematic: bloodmagic:standard/small_smithy
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6f325f27
Loading schematic: bloodmagic:standard/tall_spiral
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@3d5bd81b
Loading schematic: bloodmagic:standard/small_arena
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@111a2a8b
Loading schematic: bloodmagic:standard/antechamber
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@499c04c0
Loading schematic: bloodmagic:standard/destroyed_end_portal
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@6ad2f9c1
Loading schematic: bloodmagic:standard/four_way_corridor_loot
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@62d5e9f0
Loading schematic: bloodmagic:t3_entrance
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@14256059
Loading schematic: bloodmagic:standard_entrance
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@4524b64c
Loading schematic: bloodmagic:default_deadend
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@38aa3f10
Loading schematic: bloodmagic:mines/deadend
Resulting dungeon: wayoftime.bloodmagic.structures.DungeonRoom@3f3b3d9e
# schematics: 42
[22:50:44] [modloading-worker-0/INFO] [PluginManager/]: Executing phase INIT for plugin class TOPPlugin
[22:50:44] [modloading-worker-0/INFO] [PluginManager/]: Executing phase POST_INIT for plugin class TOPPlugin
[22:50:44] [modloading-worker-0/INFO] [co.tt.re.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[22:50:44] [modloading-worker-0/INFO] [KubeJS Startup/]: Loaded script startup_scripts:customMekanism.js in 0.3 s
[22:50:44] [modloading-worker-0/INFO] [KubeJS Startup/]: Loaded script startup_scripts:custom_stuff.js in 0.004 s
[22:50:44] [modloading-worker-0/INFO] [KubeJS Startup/]: Loaded script startup_scripts:worldgen.js in 0.002 s
[22:50:44] [modloading-worker-0/INFO] [KubeJS Startup/]: Loaded 3/3 KubeJS startup scripts in 1.74 s
[22:50:44] [modloading-worker-0/WARN] [KubeJS Startup/]: Class filter is disabled!

**Comment by SpongeFun0721** [comment]
#sometimes
java.net.ConnectException: Connection timed out
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[22:58:03] [ Iron Furnaces Update Checker/ERROR] [ir.IronFurnaces/]: Update Check failed!
java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?] {}
        at sun.nio.ch.Net.connect(Net.java:579) ~[?:?] {}
        at sun.nio.ch.Net.connect(Net.java:568) ~[?:?] {}
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?] {}
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?] {}
        at java.net.Socket.connect(Socket.java:633) ~[?:?] {}
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?] {}
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?] {}
        at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?] {}
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?] {}
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?] {}
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?] {}
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?] {}
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?] {}
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?] {}
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?] {}
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?] {}
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?] {}
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?] {}
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?] {}
        at java.net.URL.openStream(URL.java:1161) ~[?:?] {}
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at ironfurnaces.update.ThreadUpdateChecker.run(ThreadUpdateChecker.java:30) [ironfurnaces-1.18.2-3.3.3.jar%23152!/:3.3.3] {re:classloading}
        at java.base/java.net.URL.openStream(URL.java:1161)
        at TRANSFORMER/titanium@3.5.8/com.hrznstudio.titanium.util.URLUtil.readUrl(URLUtil.java:20)
        at TRANSFORMER/titanium@3.5.8/com.hrznstudio.titanium.reward.Reward.getPlayers(Reward.java:43)
        at TRANSFORMER/titanium@3.5.8/com.hrznstudio.titanium.reward.Reward.<init>(Reward.java:35)
        at TRANSFORMER/industrialforegoing@3.3.1.6/com.buuz135.industrial.IndustrialForegoing.<init>(IndustrialForegoing.java:123)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.10/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67)
        at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
